version: '3'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: office

  ldap:
    image: rroemhild/test-openldap

  app:
    image: hoelshare/office-core:latest
    env_file:
      - core/.env
    depends_on:
      - database
      - ldap
    links:
      - database:mysql
      - ldap:ldap
    ports:
      - 127.0.0.1:9042:80

  ui:
    image: hoelshare/office-ui:latest
    ports:
      - 127.0.0.1:9043:80
