version: '3'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: office

  proxy:
    build: proxy
    environment:
      APP_URL: localhost
      USE_SSL:
    links:
      - app:app
      - ui:ui
    volumes:
      - ./certs:/etc/ssl/private
    ports:
      - 80:80
      - 443:443

  app:
    image: hoelshare/office-core:latest
    env_file:
      - core/.env
    hostname: app
    environment:
      AUTH_SERVICE: saml
    depends_on:
      - database
    links:
      - database:mysql

  ui:
    image: hoelshare/office-ui:latest
    hostname: ui
    environment:
      VUE_APP_API_BASE_URL: http://localhost
      VUE_APP_AUTH_METHOD: saml
