version: '3'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: office

  app:
    image: hoelshare/office-core:latest
    env_file:
      - core/.env
    environment:
      SIMPLESAMLPHP_CONFIG_DIR: /app/config
      AUTH_SERVICE: saml
    depends_on:
      - database
    links:
      - database:mysql
    ports:
      - 127.0.0.1:9042:80

  ui:
    image: hoelshare/office-ui:latest
    ports:
      - 127.0.0.1:9043:80
